/**
 * Created by venkatsrinag on 24/4/17.
 */
import SimpleSchema from "simpl-schema";

MlFunderPortfolio = new Mongo.Collection('mlFunderPortfolio');

funderAbout = new SimpleSchema({
    firstName:{
        type:String,
        optional:true
    },
    isFirstNamePrivate:{
        type:Boolean,
        optional:true
    },
    lastName:{
        type:String,
        optional:true
    },
    isLirstNamePrivate:{
        type:Boolean,
        optional:true
    },
    gender:{
        type:String,
        optional:true
    },
    isGenderPrivate:{
        type:Boolean,
        optional:true
    },
    category:{
        type:String,
        optional:true
    },
    isCategoryPrivate:{
        type:Boolean,
        optional:true
    },
    qualification:{
        type:String,
        optional:true
    },
    isQualificationPrivate:{
        type:Boolean,
        optional:true
    },
    employmentStatus:{
        type:String,
        optional:true
    },
    isEmploymentStatusPrivate:{
        type:Boolean,
        optional:true
    },
    professionalTag:{
        type:String,
        optional:true
    },
    isProfessionalTagPrivate:{
        type:Boolean,
        optional:true
    },
    yearsOfExperience:{
        type:String,
        optional:true
    },
    isYearsOfExperiencePrivate:{
        type:Boolean,
        optional:true
    },
    industry:{
        type:String,
        optional:true
    },
    isIndustryPrivate:{
        type:Boolean,
        optional:true
    },
    profession:{
        type:String,
        optional:true
    },
    isProfessionPrivate:{
        type:Boolean,
        optional:true
    },
    investmentForm:{
        type:String,
        optional:true
    },
    investmentCount:{
        type:String,
        optional:true
    },
    isInvestmentCountPrivate:{
        type:Boolean,
        optional:true
    },
    emailId:{
        type:String,
        optional:true
    },
    isEmailIdPrivate:{
        type:Boolean,
        optional:true
    },
    mobileNumber:{
        type:Number,
        optional:true
    },
    isMobileNumberPrivate:{
        type:Boolean,
        optional:true
    },
    linkedinUrl:{
        type:String,
        optional:true
    },
    isLinkedinUrlPrivate:{
        type:Boolean,
        optional:true
    },
    facebookUrl:{
        type:String,
        optional:true
    },
    isFacebookUrlPrivate:{
        type:Boolean,
        optional:true
    },

    investmentBudget:{
        type:Object,
        optional:true
    },

    "investmentBudget.from":{
        type:String,
        optional:true
    },

    "investmentBudget.isFromPrivate":{
        type:Boolean,
        optional:true
    },

    "investmentBudget.to":{
        type:String,
        optional:true
    },

    "investmentBudget.isToPrivate":{
        type:Boolean,
        optional:true
    }
})

investments = new SimpleSchema({
    dateOfInvestment:{
        type:String,
        optional:true
    },
    companyName:{
        type:String,
        optional:true
    },
    isCompanyNamePrivate:{
        type:Boolean,
        optional:true
    },
    typeOfFunding:{
        type:String,
        optional:true
    },
    istypeOfFundingPrivate:{
        type:Boolean,
        optional:true
    },
    aboutInvestment:{
        type:String,
        optional:true
    },
    isaboutInvestmentPrivate:{
        type:Boolean,
        optional:true
    },
    isPivate:{
        type:Boolean,
        optional:true
    }
})

principal = new SimpleSchema({
    title:{
        type:String,
        optional:true
    },
    firstName:{
        type:String,
        optional:true
    },
    isFirstNamePrivate:{
        type:Boolean,
        optional:true
    },
    lastName:{
        type:String,
        optional:true
    },
    isLastNamePrivate:{
        type:Boolean,
        optional:true
    },
    designation:{
        type:String,
        optional:true
    },
    isDesignationPrivate:{
        type:Boolean,
        optional:true
    },
    companyName:{
        type:String,
        optional:true
    },
    duration:{
        type:String,
        optional:true
    },
    isDurationPrivate:{
        type:Boolean,
        optional:true
    },
    yearsOfExperience:{
        type:String,
        optional:true
    },
    isYearsOfExperiencePrivate:{
        type:Boolean,
        optional:true
    },
    qualification:{
        type:String,
        optional:true
    },
    isQualificationPrivate:{
        type:Boolean,
        optional:true
    },
    aboutPrincipal:{
        type:String,
        optional:true
    },
    isAboutPrincipalPrivate:{
        type:Boolean,
        optional:true
    },

    socialLinks:{
        type:Array,
        optional:String
    },

    'socialLinks.$':{
        type:Object,
        optional:true
    },

    'socialLinks.$.socialLinkType':{
      type:String,
      optional:true
    },

    'socialLinks.$.userId':{
        type:String,
        optional:true
    },

    'socialLinks.$.isuserIdPrivate':{
        type:Boolean,
        optional:true
    }
})

team = new SimpleSchema({
    title:{
        type:String,
        optional:true
    },
    firstName:{
        type:String,
        optional:true
    },
    isFirstNamePrivate:{
        type:Boolean,
        optional:true
    },
    lastName:{
        type:String,
        optional:true
    },
    isLastNamePrivate:{
        type:Boolean,
        optional:true
    },
    designation:{
        type:String,
        optional:true
    },
    isDesignationPrivate:{
        type:Boolean,
        optional:true
    },
    companyName:{
        type:String,
        optional:true
    },
    duration:{
        type:String,
        optional:true
    },
    isDurationPrivate:{
        type:Boolean,
        optional:true
    },
    yearsOfExperience:{
        type:String,
        optional:true
    },
    isYearsOfExperiencePrivate:{
        type:Boolean,
        optional:true
    },
    qualification:{
        type:String,
        optional:true
    },
    isQualificationPrivate:{
        type:Boolean,
        optional:true
    },
    aboutTeam:{
        type:String,
        optional:true
    },
    isAboutTeamPrivate:{
        type:Boolean,
        optional:true
    },

    socialLinks:{
        type:Array,
        optional:String
    },

    'socialLinks.$.':{
        type:Object,
        optional:true
    },

    'socialLinks.$.socialLinkType':{
        type:String,
        optional:true
    },

    'socialLinks.$.userId':{
        type:String,
        optional:true
    },

    'socialLinks.$.isuserIdPrivate':{
        type:Boolean,
        optional:true
    }
})

areaofInterest = new SimpleSchema({
    industryType:{
        type:String,
        optional:true
    },

    domainType:{
       type:String,
       optional:true
    },

    domainType:{
        type:Boolean,
        optional:true
    },

    isActive:{
        type:Boolean,
        optional:true
    }
})

successStories = new SimpleSchema({
    date:{
        type:String,
        optional:true
    },
    storyImage:{
        type:String,
        optional:true
    },
    storyTitle:{
        type:String,
        optional:true
    },
    isStoryTitlePrivate:{
        type:Boolean,
        optional:true
    },
    description:{
        type:String,
        optional:true
    },
    isDescPrivate:{
        type:Boolean,
        optional:true
    },
    makePrivate:{
        type:Boolean,
        optional:true
    },
    isActive:{
        type:Boolean,
        optional:true
    }
})

FunderPortfolioSchema = new SimpleSchema({
    funderAbout:{
        type:funderAbout,
        optional: true
    },

    investments:{
        type:Array,
        optional:true
    },

    "investments.$":{
        type:investments,
        optional:true
    },

    principal:{
        type:Array,
        optional:true
    },

    "principal.$":{
        type:principal,
        optional:true
    },

    team:{
        type:Array,
        optional:true
    },

    "team.$":{
        type:team,
        optional:true
    },

    areaofInterest:{
        type:Array,
        optional:true
    },

    "areaofInterest.$":{
        type:areaofInterest,
        optional:true
    },

    successStories:{
        type:Array,
        optional:true
    },

    "successStories.$":{
        type:successStories,
        optional:true
    }
})

MlFunderPortfolio.attachSchema(FunderPortfolioSchema);
